Commented preview deploy

diff --git a/.github/workflows/preview.yml b/.github/workflows/preview.yml
--- a/.github/workflows/preview.yml
+++ b/.github/workflows/preview.yml
@@ -1,136 +1,136 @@
-# To get started with Gatsby see: https://www.gatsbyjs.com/docs/quick-start/
+## To get started with Gatsby see: https://www.gatsbyjs.com/docs/quick-start/
+##
+#name: CI/CD Preview
+#env:
+#  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
+#  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
 #
-name: CI/CD Preview
-env:
-  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
-  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
-
-on:
-  # Runs on pushes targeting the default branch
-  push:
-    branches-ignore: [ "main" ]
-
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
-
-# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
-permissions:
-  contents: read
-  pages: write
-  id-token: write
-
-# Allow only one concurrent deployment, skipping runs queued between the run in progress and latest queued.
-# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
-concurrency:
-  group: "pages"
-  cancel-in-progress: false
-
-# Default to bash
-defaults:
-  run:
-    shell: bash
-
-jobs:
-  # Build job
-  build:
-    name: Build Site 🛠️
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout 🛎️
-        uses: actions/checkout@v4
-      - name: Detect package manager
-        id: detect-package-manager
-        run: |
-          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-            echo "manager=yarn" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            echo "runner=yarn" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "${{ github.workspace }}/package.json" ]; then
-            echo "manager=npm" >> $GITHUB_OUTPUT
-            echo "command=ci" >> $GITHUB_OUTPUT
-            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-            exit 0
-          else
-            echo "Unable to determine package manager"
-            exit 1
-          fi
-
-      - name: Setup Node.js 🏗️
-        uses: actions/setup-node@v4
-        with:
-          node-version: "20"
-          cache: ${{ steps.detect-package-manager.outputs.manager }}
-      - name: Restore cache
-        uses: actions/cache@v4
-        with:
-          path: |
-            .next/cache
-          # Generate a new cache whenever packages or source files change.
-          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
-          # If source files changed but packages didn't, rebuild from a prior cache.
-          restore-keys: |
-            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
-      - name: Install dependencies
-        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
-      - name: Set Environment Variables
-        env:
-          NEXT_PUBLIC_WORDPRESS_API_URL: ${{ secrets.NEXT_PUBLIC_WORDPRESS_API_URL }}
-          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
-          EMAIL_USER: ${{ secrets.EMAIL_USER }}
-          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
-          EMAIL_SEND_TO: ${{ secrets.EMAIL_SEND_TO }}
-        run: |
-          echo "" > .env.production
-          echo NEXT_PUBLIC_WORDPRESS_API_URL="$NEXT_PUBLIC_WORDPRESS_API_URL" >> .env.production
-          echo EMAIL_HOST="$EMAIL_HOST" >> .env.production
-          echo EMAIL_USER="$EMAIL_USER" >> .env.production
-          echo EMAIL_PASS="$EMAIL_PASS" >> .env.production
-          echo EMAIL_SEND_TO="$EMAIL_SEND_TO" >> .env.production
-      - name: Build with Next.js
-        run: ${{ steps.detect-package-manager.outputs.runner }} next build
-
-
-  # Jest job
-  test:
-    name: Unit Tests 🧪
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-node@v4
-        with:
-          node-version: '20'
-      - run: npm ci
-      - run: npm cache verify
-      - run: npm run test
-
-  # Deployment job
-  deploy:
-    name: Deploy (Preview) 🚀
-    needs: [ build, test ]
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-      - name: Install Vercel CLI
-        run: npm install --global vercel@latest
-      - name: Pull Vercel Environment Information
-        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
-      - name: Set Environment Variables
-        env:
-          NEXT_PUBLIC_WORDPRESS_API_URL: ${{ secrets.NEXT_PUBLIC_WORDPRESS_API_URL }}
-          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
-          EMAIL_USER: ${{ secrets.EMAIL_USER }}
-          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
-          EMAIL_SEND_TO: ${{ secrets.EMAIL_SEND_TO }}
-        run: |
-          echo "" > .env.production
-          echo NEXT_PUBLIC_WORDPRESS_API_URL="$NEXT_PUBLIC_WORDPRESS_API_URL" >> .env.production
-          echo EMAIL_HOST="$EMAIL_HOST" >> .env.production
-          echo EMAIL_USER="$EMAIL_USER" >> .env.production
-          echo EMAIL_PASS="$EMAIL_PASS" >> .env.production
-          echo EMAIL_SEND_TO="$EMAIL_SEND_TO" >> .env.production
-      - name: Build Project Artifacts
-        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
-      - name: Deploy Project Artifacts to Vercel
-        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
+#on:
+#  # Runs on pushes targeting the default branch
+#  push:
+#    branches-ignore: [ "main" ]
+#
+#  # Allows you to run this workflow manually from the Actions tab
+#  workflow_dispatch:
+#
+## Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
+#permissions:
+#  contents: read
+#  pages: write
+#  id-token: write
+#
+## Allow only one concurrent deployment, skipping runs queued between the run in progress and latest queued.
+## However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
+#concurrency:
+#  group: "pages"
+#  cancel-in-progress: false
+#
+## Default to bash
+#defaults:
+#  run:
+#    shell: bash
+#
+#jobs:
+#  # Build job
+#  build:
+#    name: Build Site 🛠️
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Checkout 🛎️
+#        uses: actions/checkout@v4
+#      - name: Detect package manager
+#        id: detect-package-manager
+#        run: |
+#          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+#            echo "manager=yarn" >> $GITHUB_OUTPUT
+#            echo "command=install" >> $GITHUB_OUTPUT
+#            echo "runner=yarn" >> $GITHUB_OUTPUT
+#            exit 0
+#          elif [ -f "${{ github.workspace }}/package.json" ]; then
+#            echo "manager=npm" >> $GITHUB_OUTPUT
+#            echo "command=ci" >> $GITHUB_OUTPUT
+#            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+#            exit 0
+#          else
+#            echo "Unable to determine package manager"
+#            exit 1
+#          fi
+#
+#      - name: Setup Node.js 🏗️
+#        uses: actions/setup-node@v4
+#        with:
+#          node-version: "20"
+#          cache: ${{ steps.detect-package-manager.outputs.manager }}
+#      - name: Restore cache
+#        uses: actions/cache@v4
+#        with:
+#          path: |
+#            .next/cache
+#          # Generate a new cache whenever packages or source files change.
+#          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+#          # If source files changed but packages didn't, rebuild from a prior cache.
+#          restore-keys: |
+#            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
+#      - name: Install dependencies
+#        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+#      - name: Set Environment Variables
+#        env:
+#          NEXT_PUBLIC_WORDPRESS_API_URL: ${{ secrets.NEXT_PUBLIC_WORDPRESS_API_URL }}
+#          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
+#          EMAIL_USER: ${{ secrets.EMAIL_USER }}
+#          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
+#          EMAIL_SEND_TO: ${{ secrets.EMAIL_SEND_TO }}
+#        run: |
+#          echo "" > .env.production
+#          echo NEXT_PUBLIC_WORDPRESS_API_URL="$NEXT_PUBLIC_WORDPRESS_API_URL" >> .env.production
+#          echo EMAIL_HOST="$EMAIL_HOST" >> .env.production
+#          echo EMAIL_USER="$EMAIL_USER" >> .env.production
+#          echo EMAIL_PASS="$EMAIL_PASS" >> .env.production
+#          echo EMAIL_SEND_TO="$EMAIL_SEND_TO" >> .env.production
+#      - name: Build with Next.js
+#        run: ${{ steps.detect-package-manager.outputs.runner }} next build
+#
+#
+#  # Jest job
+#  test:
+#    name: Unit Tests 🧪
+#    runs-on: ubuntu-latest
+#    needs: build
+#    steps:
+#      - uses: actions/checkout@v4
+#      - uses: actions/setup-node@v4
+#        with:
+#          node-version: '20'
+#      - run: npm ci
+#      - run: npm cache verify
+#      - run: npm run test
+#
+#  # Deployment job
+#  deploy:
+#    name: Deploy (Preview) 🚀
+#    needs: [ build, test ]
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v2
+#      - name: Install Vercel CLI
+#        run: npm install --global vercel@latest
+#      - name: Pull Vercel Environment Information
+#        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
+#      - name: Set Environment Variables
+#        env:
+#          NEXT_PUBLIC_WORDPRESS_API_URL: ${{ secrets.NEXT_PUBLIC_WORDPRESS_API_URL }}
+#          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
+#          EMAIL_USER: ${{ secrets.EMAIL_USER }}
+#          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
+#          EMAIL_SEND_TO: ${{ secrets.EMAIL_SEND_TO }}
+#        run: |
+#          echo "" > .env.production
+#          echo NEXT_PUBLIC_WORDPRESS_API_URL="$NEXT_PUBLIC_WORDPRESS_API_URL" >> .env.production
+#          echo EMAIL_HOST="$EMAIL_HOST" >> .env.production
+#          echo EMAIL_USER="$EMAIL_USER" >> .env.production
+#          echo EMAIL_PASS="$EMAIL_PASS" >> .env.production
+#          echo EMAIL_SEND_TO="$EMAIL_SEND_TO" >> .env.production
+#      - name: Build Project Artifacts
+#        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
+#      - name: Deploy Project Artifacts to Vercel
+#        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
